feat: support more extended use cases for the comment syntax
stackblitz/eslint-plugin pull request #7
Opened 2022-02-08 19:53 UTC by KwintenP

Added support for all use cases in the webcontainer repo.

- option for words to be ignored
- support for jsdoc
- support for `#region` end `#endregion`
- ignores single line block comments so this is allowed `foo(bar /** explainer what this is*/)`
maybe some other stuff.

Also added to the recommended rules.
Actually tested against webcontainer to be sure this time.

2022-02-08 19:55 UTC, KwintenP commented
Btw, again, still tried to avoid using a regex but it's getting to the point where, if more is added, I'd prolly switch... 
Would simplify the code but I think it's manageable for now.

2022-02-09 07:56 UTC, d3lm commented on src/rules/comment.ts
> +    lineCommentAllowedCapitalisedWords: string[];
Maybe we call this option just `allowedWords`? WDYT?

2022-02-09 07:58 UTC, KwintenP commented on src/rules/comment.ts
> +    lineCommentAllowedCapitalisedWords: string[];
Yeah, didn't really like the name either. Had no inspiration at the time.

Maybe `ignoredWords` is even better?

2022-02-09 07:58 UTC, d3lm commented on src/rules/comment.ts
> +    lineCommentAllowedCapitalisedWords: string[];
Yep, `ignoredWords` works too 👍

2022-02-09 08:42 UTC, jrvidal approved these changes

2022-02-10 16:51 UTC, SamVerschueren approved these changes

2022-02-14 12:39 UTC, d3lm requested changes
Just the comment I made about the option name, otherwise LGTM.

2022-02-14 13:01 UTC, KwintenP commented on src/rules/comment.ts
> +    lineCommentAllowedCapitalisedWords: string[];
Updated!

2022-02-14 14:13 UTC, d3lm approved these changes

2022-02-14 14:13 UTC, merged